### ISSUE TITLE
Suggested Bridge height

### ISSUE THREAD

**Issue by renpre98** [ds5678/BleakBridge#1]
![grafik](https://user-images.githubusercontent.com/42774556/107277796-36dab780-6a55-11eb-9160-6d137c750ac9.png)

As you can see in the picture I chaged the height of the bridgeblocks so that they integrate into the Pier.  
I set the height to 31.3900f. I just wanted to let you know.

**Comment by ds5678** [comment]
I'll try it out.

**Comment by ds5678** [comment]
It worked great. I changed it.
